import 'swiper/css';
import "swiper/css/navigation";
import "swiper/css/pagination";
import "/public/assets/css/style.css"
import "/public/assets/css/components.css"
import "/public/assets/css/widgets.css"
import "/public/assets/css/responsive.css"
import { Barlow, Crimson_Text } from 'next/font/google'

const barlow = Barlow({
    weight: ['300', '400', '500', '600', '700'],
    subsets: ['latin'],
    variable: "--font-primary",
})
const crimson = Crimson_Text({
    weight: [ '400', '600', '700'],
    subsets: ['latin'],
    variable: "--font-secondary",
})
export const metadata = {
  title: 'Athena - Minimal Blog Next Template',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${barlow.variable} ${crimson.variable}`}>{children}</body>
    </html>
  )
}
